# -*- coding: utf-8 -*-
"""code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1me3lfX3JMxWVZF-WxBvTC9WFV9RgCBJm

**Logistic regression model**
"""

# ✅ STEP 1: Install kagglehub
!pip install -q kagglehub
# ✅ STEP 2: Download dataset via kagglehub
import kagglehub
import os
import shutil
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                    random_state=1)
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])

clf.predict(X_test[:5, :])

clf.score(X_test, y_test)


# Download the dataset
download_path = kagglehub.dataset_download("aryansinghal10/alzheimers-multiclass-dataset-equal-and-augmented")
print("✅ Dataset downloaded to:", download_path)

# Define a writable path in Colab
writable_path = "/content/alzheimers_dataset"

# Copy the dataset to a writable location
if os.path.exists(writable_path):
    shutil.rmtree(writable_path) # Remove if already exists
shutil.copytree(download_path, writable_path)
print(f"✅ Dataset copied to writable location: {writable_path}")

# Use the writable path for the rest of the code
path = writable_path

# ✅ STEP 3: Split combined_images into train/test folders
import shutil
import random

combined_path = os.path.join(path, "combined_images")
train_path = os.path.join(path, "train")
test_path = os.path.join(path, "test")

os.makedirs(train_path, exist_ok=True)
os.makedirs(test_path, exist_ok=True)

split_ratio = 0.8
for class_name in os.listdir(combined_path):
    class_dir = os.path.join(combined_path, class_name)
    if not os.path.isdir(class_dir):
        continue
    images = os.listdir(class_dir)
    random.shuffle(images)
    split_index = int(len(images) * split_ratio)
    train_imgs = images[:split_index]
    test_imgs = images[split_index:]

    os.makedirs(os.path.join(train_path, class_name), exist_ok=True)
    os.makedirs(os.path.join(test_path, class_name), exist_ok=True)

    for img in train_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(train_path, class_name, img))
    for img in test_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(test_path, class_name, img))

print("✅ Train/test split created.")
# ✅ STEP 4: Load and flatten images with size + count limits
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array

img_size = (50, 50)  # Small image size
MAX_IMAGES_PER_CLASS = 500  # Limit per class

def load_images_from_directory(directory):
    X, y = [], []
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if not os.path.isdir(class_path): continue

        count = 0
        for filename in os.listdir(class_path):
            if count >= MAX_IMAGES_PER_CLASS:
                break
            file_path = os.path.join(class_path, filename)
            try:
                img = load_img(file_path, target_size=img_size)
                img_array = img_to_array(img) / 255.0
                X.append(img_array.flatten())
                y.append(class_name)
                count += 1
            except Exception as e:
                print("Skipping:", file_path, "| Error:", e)
    return np.array(X), np.array(y)

print("📥 Loading training data...")
X_train, y_train = load_images_from_directory(train_path)

print("📥 Loading test data...")
X_test, y_test = load_images_from_directory(test_path)

print("✅ Data loaded.")
print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)
# ✅ STEP 5: Encode labels and apply PCA for dimensionality reduction
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA

encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)

print("🎯 Classes:", encoder.classes_)

# Use PCA to reduce dimensions
pca = PCA(n_components=100)  # reduce features to 100
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print("✅ PCA applied. New shapes:")
print("X_train_pca:", X_train_pca.shape)
# ✅ STEP 6: Train and evaluate logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

model = LogisticRegression(max_iter=10000, solver='newton-cg', multi_class='multinomial')
print("🚀 Training logistic regression...")
model.fit(X_train_pca, y_train_enc)
print("✅ Model trained.")

# Evaluate
y_pred = model.predict(X_test_pca)
y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc)

print("\n📊 Classification Report:")
print(classification_report(y_test_labels, y_pred_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_test_labels, y_pred_labels))

sns.histplot(data=y_test)

"""**random forest classifier**"""

# ✅ STEP 1: Install kagglehub
!pip install -q kagglehub
# ✅ STEP 2: Download dataset from kagglehub
import kagglehub
import os
import shutil # Import shutil
from sklearn.ensemble import RandomForestClassifier # Import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix # Import metrics
from sklearn.preprocessing import LabelEncoder # Import LabelEncoder
from sklearn.decomposition import PCA # Import PCA
import numpy as np # Import numpy
from tensorflow.keras.preprocessing.image import load_img, img_to_array # Import image processing tools


# Download the dataset
download_path = kagglehub.dataset_download("aryansinghal10/alzheimers-multiclass-dataset-equal-and-augmented")
print("✅ Dataset downloaded to:", download_path)

# Define a writable path in Colab
writable_path = "/content/alzheimers_dataset_rf" # Use a different path for this model to avoid conflicts

# Copy the dataset to a writable location
if os.path.exists(writable_path):
    shutil.rmtree(writable_path) # Remove if already exists
shutil.copytree(download_path, writable_path)
print(f"✅ Dataset copied to writable location: {writable_path}")

# Use the writable path for the rest of the code
path = writable_path

# ✅ STEP 3: Train/Test split from combined_images/
combined_path = os.path.join(path, "combined_images")
train_path = os.path.join(path, "train")
test_path = os.path.join(path, "test")

os.makedirs(train_path, exist_ok=True)
os.makedirs(test_path, exist_ok=True)

split_ratio = 0.7

for class_name in os.listdir(combined_path):
    class_dir = os.path.join(combined_path, class_name)
    if not os.path.isdir(class_dir):
        continue
    images = os.listdir(class_dir)
    random.shuffle(images)

    split_index = int(len(images) * split_ratio)
    train_imgs = images[:split_index]
    test_imgs = images[split_index:]

    os.makedirs(os.path.join(train_path, class_name), exist_ok=True)
    os.makedirs(os.path.join(test_path, class_name), exist_ok=True)

    for img in train_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(train_path, class_name, img))
    for img in test_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(test_path, class_name, img))

print("✅ Train/test split created.")

# ✅ STEP 4: Load and flatten images (with limits)
img_size = (64, 64)
MAX_IMAGES_PER_CLASS = 500

def load_images_from_directory(directory):
    X, y = [], []
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if not os.path.isdir(class_path): continue
        count = 0
        for filename in os.listdir(class_path):
            if count >= MAX_IMAGES_PER_CLASS:
                break
            file_path = os.path.join(class_path, filename)
            try:
                img = load_img(file_path, target_size=img_size)
                img_array = img_to_array(img) / 255.0
                X.append(img_array.flatten())
                y.append(class_name)
                count += 1
            except Exception as e:
                print("Skipping:", file_path, "| Error:", e)
    return np.array(X), np.array(y)

print("📥 Loading training data...")
X_train, y_train = load_images_from_directory(train_path)

print("📥 Loading test data...")
X_test, y_test = load_images_from_directory(test_path)

print("✅ Data loaded.")
print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)

# ✅ STEP 5: Encode labels and reduce dimensionality with PCA
encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)

print("🎯 Classes:", encoder.classes_)

# PCA
pca = PCA(n_components=200)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print("✅ PCA complete.")
print("X_train_pca shape:", X_train_pca.shape)

# ✅ STEP 6: Train Random Forest and evaluate
model = RandomForestClassifier(n_estimators=10000, max_depth=20, random_state=42,)

print("🚀 Training Random Forest...")
model.fit(X_train_pca, y_train_enc)
print("✅ Model trained.")

y_pred = model.predict(X_test_pca)
y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc)

print("\n📊 Classification Report:")
print(classification_report(y_test_labels, y_pred_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_test_labels, y_pred_labels))

"""rf w/ resnet 50"""

from tensorflow.keras.applications import VGG16, ResNet50
from tensorflow.keras.applications.vgg16 import preprocess_input as vgg_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import os
import kagglehub
import shutil
import random

# -----------------
# 1. Download and prepare data
# -----------------
# Download the dataset
download_path = kagglehub.dataset_download("aryansinghal10/alzheimers-multiclass-dataset-equal-and-augmented")
print("✅ Dataset downloaded to:", download_path)

# Define a writable path in Colab
writable_path = "/content/alzheimers_dataset_cnn" # Use a different path for this model

# Copy the dataset to a writable location
if os.path.exists(writable_path):
    shutil.rmtree(writable_path) # Remove if already exists
shutil.copytree(download_path, writable_path)
print(f"✅ Dataset copied to writable location: {writable_path}")

# Use the writable path for the rest of the code
path = writable_path

# Train/Test split from combined_images/
combined_path = os.path.join(path, "combined_images")
train_path = os.path.join(path, "train")
test_path = os.path.join(path, "test")

os.makedirs(train_path, exist_ok=True)
os.makedirs(test_path, exist_ok=True)

split_ratio = 0.7

for class_name in os.listdir(combined_path):
    class_dir = os.path.join(combined_path, class_name)
    if not os.path.isdir(class_dir):
        continue
    images = os.listdir(class_dir)
    random.shuffle(images)

    split_index = int(len(images) * split_ratio)
    train_imgs = images[:split_index]
    test_imgs = images[split_index:]

    os.makedirs(os.path.join(train_path, class_name), exist_ok=True)
    os.makedirs(os.path.join(test_path, class_name), exist_ok=True)

    for img in train_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(train_path, class_name, img))
    for img in test_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(test_path, class_name, img))

print("✅ Train/test split created.")


# -----------------
# 2. Load pretrained CNNs (feature extractors)
# -----------------
vgg_base = VGG16(weights="imagenet", include_top=False, pooling="avg", input_shape=(224, 224, 3))
resnet_base = ResNet50(weights="imagenet", include_top=False, pooling="avg", input_shape=(224, 224, 3))

# -----------------
# 3. Feature extractor function
# -----------------
def extract_features(directory, model, preprocess_func, img_size=(224, 224), max_images=500):
    X, y = [], []
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if not os.path.isdir(class_path):
            continue
        count = 0
        for filename in os.listdir(class_path):
            if count >= max_images:
                break
            try:
                img = load_img(os.path.join(class_path, filename), target_size=img_size)
                img_array = img_to_array(img)
                img_array = np.expand_dims(img_array, axis=0)
                img_array = preprocess_func(img_array)
                features = model.predict(img_array, verbose=0)
                X.append(features.flatten())
                y.append(class_name)
                count += 1
            except Exception as e:
                print("Skipping:", filename, "| Error:", e)
    return np.array(X), np.array(y)

# -----------------
# 4. Extract features for VGG16
# -----------------
print("📥 Extracting VGG16 features...")

X_test_vgg, y_test_vgg = extract_features(test_path, vgg_base, vgg_preprocess)

# -----------------
# 5. Extract features for ResNet50
# -----------------
print("📥 Extracting ResNet50 features...")
X_train_resnet, y_train_resnet = extract_features(train_path, resnet_base, resnet_preprocess)
X_test_resnet, y_test_resnet = extract_features(test_path, resnet_base, resnet_preprocess)

# -----------------
# 6. Encode labels
# -----------------
encoder = LabelEncoder()


y_train_resnet_enc = encoder.fit_transform(y_train_resnet)
y_test_resnet_enc = encoder.transform(y_test_resnet)


print("🎯 Classes:", encoder.classes_)



# -----------------
# 8. Train RandomForest on ResNet50 features
# -----------------
rf_resnet = RandomForestClassifier(n_estimators=1000, max_depth=30, random_state=42)
rf_resnet.fit(X_train_resnet, y_train_resnet_enc)

y_pred_resnet = encoder.inverse_transform(rf_resnet.predict(X_test_resnet))

print("\n📊 ResNet50 + RF Report:")
print(classification_report(y_test_resnet, y_pred_resnet))
print(confusion_matrix(y_test_resnet, y_pred_resnet))

"""rf (vgg16) iso"""

# -----------------
# 4. Extract features for VGG16
# -----------------
print("📥 Extracting VGG16 features...")

X_test_vgg, y_test_vgg = extract_features(test_path, vgg_base, vgg_preprocess)
X_train_vgg, y_train_vgg = extract_features(train_path, vgg_base, vgg_preprocess)

#6
y_train_vgg_enc = encoder.fit_transform(y_train_vgg)
y_test_vgg_enc = encoder.transform(y_test_vgg)


# -----------------
# 7. Train RandomForest on VGG16 features
# -----------------
rf_vgg = RandomForestClassifier(n_estimators=1000, max_depth=30, random_state=42)
rf_vgg.fit(X_train_vgg, y_train_vgg_enc)

y_pred_vgg = encoder.inverse_transform(rf_vgg.predict(X_test_vgg))

print("\n📊 VGG16 + RF Report:")
print(classification_report(y_test_vgg, y_pred_vgg))
print(confusion_matrix(y_test_vgg, y_pred_vgg))

"""rf with resnet 50"""



"""resnet mlp"""

# --- Load features for ResNet50 ---
X_train_res, y_train_res = extract_features(train_path, resnet_model, resnet_preprocess)
X_test_res, y_test_res = extract_features(test_path, resnet_model, resnet_preprocess)

# Encode labels (same encoder as before)
y_train_res_enc = encoder.transform(y_train_res)
y_test_res_enc = encoder.transform(y_test_res)

# --- Build MLP ---
mlp_model_res = models.Sequential([
    layers.Input(shape=(X_train_res.shape[1],)),
    layers.Dense(512, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.4),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(len(encoder.classes_), activation="softmax")
])

mlp_model_res.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- Train ---
history_res = mlp_model_res.fit(
    X_train_res, y_train_res_enc,
    validation_split=0.2,
    epochs=30,
    batch_size=8,
    callbacks=[callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)],
    verbose=1
)

# --- Evaluate ---
y_pred_probs_res = mlp_model_res.predict(X_test_res)
y_pred_res = np.argmax(y_pred_probs_res, axis=1)

print("\n📊 ResNet50 + MLP Classification Report:")
print(classification_report(y_test_res_enc, y_pred_res, target_names=encoder.classes_))

"""MLP classifier

"""

# ✅ STEP: Train and Evaluate MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
import os
import shutil
import random
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras import models, layers, callbacks
import matplotlib.pyplot as plt
import seaborn as sns


# Define a writable path in Colab
path = "/content/alzheimers_dataset"

# Define paths for train and test data
train_path = os.path.join(path, "train")
test_path = os.path.join(path, "test")

# Define image size and limits (ensure these are consistent with data preparation)
img_size = (64, 64)
MAX_IMAGES_PER_CLASS = 500

# Function to load images
def load_images_from_directory(directory):
    X, y = [], []
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if not os.path.isdir(class_path): continue

        count = 0
        for filename in os.listdir(class_path):
            if count >= MAX_IMAGES_PER_CLASS:
                break
            file_path = os.path.join(class_path, filename)
            try:
                img = load_img(file_path, target_size=img_size)
                img_array = img_to_array(img) / 255.0
                X.append(img_array.flatten())
                y.append(class_name)
                count += 1
            except Exception as e:
                print("Skipping:", file_path, "| Error:", e)
    return np.array(X), np.array(y)

# Load data
print("📥 Loading training data...")
X_train, y_train = load_images_from_directory(train_path)

print("📥 Loading test data...")
X_test, y_test = load_images_from_directory(test_path)

print("✅ Data loaded.")
print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)

# Encode labels
encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)

print("🎯 Classes:", encoder.classes_)

# Build Improved MLP Classifier
mlp_model = models.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(512, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(256, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),

    layers.Dense(len(encoder.classes_), activation="softmax")
])

mlp_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# ✅ Callbacks
early_stop = callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
reduce_lr = callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, verbose=1)

print("🚀 Training MLP Classifier...")
history = mlp_model.fit(
    X_train, y_train_enc, # Use encoded training labels
    validation_split=0.2,
    epochs=50,
    batch_size=8,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

print("✅ Training complete.")

# ✅ STEP 9: Evaluate
y_pred_probs = mlp_model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc) # Use encoded test labels for evaluation

# --- (1) Full Classification Report
print("\n📊 Classification Report (All 4 Classes):")
print(classification_report(y_test_labels, y_pred_labels, target_names=encoder.classes_))

# --- (2) Confusion Matrix Heatmap
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=encoder.classes_)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=encoder.classes_,
            yticklabels=encoder.classes_)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

# --- (3) Highlight NonDemented vs VeryMildDemented Results
mask = (y_test_labels == "NonDemented") | (y_test_labels == "VeryMildDemented")
print("\n🎯 Focused Results: NonDemented vs VeryMildDemented")
print(classification_report(y_test_labels[mask], y_pred_labels[mask],
                            target_names=["NonDemented", "VeryMildDemented"],
                            labels=["NonDemented", "VeryMildDemented"]))

leap_year = int(input("What year is it? "))

if leap_year > 1582:
    if leap_year % 4 == 0:
        else:
        leap_year % 100 != 0  and leap_year % 400 != 0
        print("this is a leap year")
else:
    print("this year is not a leap year")

"""improved mlp

pca, mlp tuning, better learning rate
"""

# ✅ Install dependencies
!pip install -q kagglehub tensorflow scikit-learn

import kagglehub, os, shutil, numpy as np, matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models, optimizers

# -------------------------------------------------
# STEP 1: Download dataset
# -------------------------------------------------
download_path = kagglehub.dataset_download("aryansinghal10/alzheimers-multiclass-dataset-equal-and-augmented")
print("✅ Dataset downloaded to:", download_path)

# Copy to writable path
data_path = "/content/alzheimers_dataset_cnn"
if os.path.exists(data_path):
    shutil.rmtree(data_path)
shutil.copytree(download_path, data_path)
print(f"✅ Dataset ready at: {data_path}")

combined_path = os.path.join(data_path, "combined_images")

# -------------------------------------------------
# STEP 2: Train/Validation/Test Split
# -------------------------------------------------
import random
train_dir = os.path.join(data_path, "train")
val_dir = os.path.join(data_path, "val")
test_dir = os.path.join(data_path, "test")

for d in [train_dir, val_dir, test_dir]:
    os.makedirs(d, exist_ok=True)

split_ratio_train = 0.7
split_ratio_val = 0.15  # 15% val, 15% test

for class_name in os.listdir(combined_path):
    class_path = os.path.join(combined_path, class_name)
    if not os.path.isdir(class_path): continue

    images = os.listdir(class_path)
    random.shuffle(images)

    n_total = len(images)
    n_train = int(n_total * split_ratio_train)
    n_val = int(n_total * split_ratio_val)

    splits = [
        (images[:n_train], train_dir),
        (images[n_train:n_train+n_val], val_dir),
        (images[n_train+n_val:], test_dir),
    ]

    for imgs, target_dir in splits:
        target_class_dir = os.path.join(target_dir, class_name)
        os.makedirs(target_class_dir, exist_ok=True)
        for img in imgs:
            shutil.copy2(os.path.join(class_path, img),
                         os.path.join(target_class_dir, img))

print("✅ Train/Val/Test split completed.")

# -------------------------------------------------
# STEP 3: Image Generators with Augmentation
# -------------------------------------------------
IMG_SIZE = (64, 64)  # typical for ResNet
BATCH_SIZE = 8

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True
)

val_test_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    train_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical'
)

val_data = val_test_gen.flow_from_directory(
    val_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical'
)

test_data = val_test_gen.flow_from_directory(
    test_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False
)

num_classes = train_data.num_classes
print("✅ Classes:", train_data.class_indices)

# -------------------------------------------------
# STEP 4: Build CNN (ResNet50 + Custom Head)
# -------------------------------------------------
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=IMG_SIZE + (3,))
base_model.trainable = False  # start with frozen base

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# -------------------------------------------------
# STEP 5: Train top layers first (warm-up)
# -------------------------------------------------
early_stop = tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10,
    callbacks=[early_stop]
)

# -------------------------------------------------
# STEP 6: Fine-tune last few ResNet blocks
# -------------------------------------------------
base_model.trainable = True
for layer in base_model.layers[:-50]:  # freeze all but last 50 layers
    layer.trainable = False

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-5),  # lower LR
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_ft = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10,
    callbacks=[early_stop]
)

# -------------------------------------------------
# STEP 7: Evaluation
# -------------------------------------------------
loss, acc = model.evaluate(test_data)
print(f"✅ Test Accuracy: {acc*100:.2f}%")

y_pred = np.argmax(model.predict(test_data), axis=1)
y_true = test_data.classes
class_labels = list(test_data.class_indices.keys())

print("\n📊 Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

"""cnn t4"""

# ✅ Install dependencies
!pip install -q kagglehub tensorflow scikit-learn

import kagglehub, os, shutil, numpy as np, matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models, optimizers

# -------------------------------------------------
# STEP 1: Download dataset
# -------------------------------------------------
download_path = kagglehub.dataset_download("aryansinghal10/alzheimers-multiclass-dataset-equal-and-augmented")
print("✅ Dataset downloaded to:", download_path)

# Copy to writable path
data_path = "/content/alzheimers_dataset_cnn"
if os.path.exists(data_path):
    shutil.rmtree(data_path)
shutil.copytree(download_path, data_path)
print(f"✅ Dataset ready at: {data_path}")

combined_path = os.path.join(data_path, "combined_images")

# -------------------------------------------------
# STEP 2: Train/Validation/Test Split
# -------------------------------------------------
import random
train_dir = os.path.join(data_path, "train")
val_dir = os.path.join(data_path, "val")
test_dir = os.path.join(data_path, "test")

for d in [train_dir, val_dir, test_dir]:
    os.makedirs(d, exist_ok=True)

split_ratio_train = 0.7
split_ratio_val = 0.15  # 15% val, 15% test

for class_name in os.listdir(combined_path):
    class_path = os.path.join(combined_path, class_name)
    if not os.path.isdir(class_path): continue

    images = os.listdir(class_path)
    random.shuffle(images)

    n_total = len(images)
    n_train = int(n_total * split_ratio_train)
    n_val = int(n_total * split_ratio_val)

    splits = [
        (images[:n_train], train_dir),
        (images[n_train:n_train+n_val], val_dir),
        (images[n_train+n_val:], test_dir),
    ]

    for imgs, target_dir in splits:
        target_class_dir = os.path.join(target_dir, class_name)
        os.makedirs(target_class_dir, exist_ok=True)
        for img in imgs:
            shutil.copy2(os.path.join(class_path, img),
                         os.path.join(target_class_dir, img))

print("✅ Train/Val/Test split completed.")

# -------------------------------------------------
# STEP 3: Image Generators with Augmentation
# -------------------------------------------------
IMG_SIZE = (224, 224)  # typical for ResNet (224, 224)
BATCH_SIZE = 128 #try 64  128

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True
)

val_test_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    train_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical'
)

val_data = val_test_gen.flow_from_directory(
    val_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical'
)

test_data = val_test_gen.flow_from_directory(
    test_dir, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False
)

num_classes = train_data.num_classes
print("✅ Classes:", train_data.class_indices)

# -------------------------------------------------
# STEP 4: Build CNN (ResNet50 + Custom Head)
# -------------------------------------------------
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=IMG_SIZE + (3,))
base_model.trainable = False  # start with frozen base

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(256, activation='tanh'),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# -------------------------------------------------
# STEP 5: Train top layers first (warm-up)
# -------------------------------------------------
early_stop = tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10,
    callbacks=[early_stop]
)

# -------------------------------------------------
# STEP 6: Fine-tune last few ResNet blocks
# -------------------------------------------------
base_model.trainable = True
for layer in base_model.layers[:-50]:  # freeze all but last 50 layers
    layer.trainable = False

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-6),  # lower LR
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_ft = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10,
    callbacks=[early_stop]
)

# -------------------------------------------------
# STEP 7: Evaluation
# -------------------------------------------------
loss, acc = model.evaluate(test_data)
print(f"✅ Test Accuracy: {acc*100:.2f}%")

y_pred = np.argmax(model.predict(test_data), axis=1)
y_true = test_data.classes
class_labels = list(test_data.class_indices.keys())

print("\n📊 Classification Report:")
print(classification_report(y_true, y_pred, target_names=class_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

"""SK LEARN modification of neurons and layers"""

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(100,), random_state=1, max_iter=300).fit(X_train, y_train)

clf.predict(X_test)
clf.score(X_test, y_test)

"""mlp test mild & mod"""

# ✅
import tensorflow as tf
from tensorflow.keras import models, layers, callbacks
from sklearn.preprocessing import LabelEncoder # Import LabelEncoder
import numpy as np # Import numpy


mlp_model = models.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(512, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(256, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),

    layers.Dense(64, activation="relu"),
    layers.Dropout(0.1),

    layers.Dense(len(encoder.classes_), activation="softmax")
])

mlp_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# ✅ Callbacks
early_stop = callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
reduce_lr = callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, verbose=1)

# Encode labels
y_train_enc = encoder.transform(y_train) # Encode training labels
y_test_enc = encoder.transform(y_test) # Encode test labels


print("🚀 Training MLP Classifier...")
history = mlp_model.fit(
    X_train, y_train_enc, # Use encoded training labels
    validation_split=0.3,
    epochs=20,
    batch_size=8,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

print("✅ Training complete.")

# ✅ STEP 9: Evaluate
y_pred_probs = mlp_model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc) # Use encoded test labels for evaluation

print("\n📊 Classification Report:")
print(classification_report(y_test_labels, y_pred_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_test_labels, y_pred_labels))

"""mlp test all 4"""

# ✅ Imports
import tensorflow as tf
from tensorflow.keras import models, layers, callbacks
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# --- (1) Encode labels properly
encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)

print("🎯 Classes found:", encoder.classes_)

# --- (2) Compute class weights (to balance smaller classes)
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train_enc),
    y=y_train_enc
)
class_weights = dict(enumerate(class_weights))
print("⚖️ Class Weights:", class_weights)

# --- (3) Define MLP Model
mlp_model = models.Sequential([
    layers.Input(shape=(X_train.shape[1],)),

    layers.Dense(512, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(256, activation="relu"),
    layers.BatchNormalization(),
    layers.Dropout(0.3),

    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),

    layers.Dense(64, activation="relu"),
    layers.Dropout(0.1),

    layers.Dense(len(encoder.classes_), activation="softmax")  # 4 outputs
])

mlp_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# --- (4) Callbacks
early_stop = callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
reduce_lr = callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, verbose=1)

# --- (5) Training
print("🚀 Training MLP Classifier...")
history = mlp_model.fit(
    X_train, y_train_enc,
    validation_split=0.2,
    epochs=500,
    batch_size=32,
    callbacks=[early_stop, reduce_lr],
    class_weight=class_weights,
    verbose=1
)
print("✅ Training complete.")

# --- (6) Evaluation
y_pred_probs = mlp_model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc)

print("\n📊 Classification Report (All 4 Classes):")
print(classification_report(y_test_labels, y_pred_labels, target_names=encoder.classes_))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_test_labels, y_pred_labels, labels=encoder.classes_))

"""decision tree classifier"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create the Decision Tree model
dt = DecisionTreeClassifier(
    criterion='gini',     # or 'entropy', 'log_loss'
    max_depth=None,       # limit depth of the tree
    min_samples_split=2,  # minimum samples required to split
    min_samples_leaf=1,   # minimum samples at a leaf node
    max_features=None,    # number of features to consider at split
    random_state=42
)

print("🚀 Training Decision Tree Classifier...")
dt.fit(X_train_pca, y_train_enc)
print("✅ Model trained.")

# Predictions
y_pred = dt.predict(X_test_pca)
y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc)

# Evaluation
print("\n📊 Classification Report:")
print(classification_report(y_test_labels, y_pred_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_test_labels, y_pred_labels))

"""SVC classifier"""

# ✅ STEP 1: Install kagglehub
!pip install -q kagglehub
# Download the dataset
download_path = kagglehub.dataset_download("aryansinghal10/alzheimers-multiclass-dataset-equal-and-augmented")
print("✅ Dataset downloaded to:", download_path)

# Define a writable path in Colab (ensure this is the same path used for data preparation)
path = "/content/alzheimers_dataset_rf" # Using the path from the Random Forest model

# Copy the dataset to a writable location
if os.path.exists(path):
    shutil.rmtree(path) # Remove if already exists
shutil.copytree(download_path, path)
print(f"✅ Dataset copied to writable location: {path}")


# ✅ STEP 2: Train/Test split from combined_images/
combined_path = os.path.join(path, "combined_images")
train_path = os.path.join(path, "train")
test_path = os.path.join(path, "test")

os.makedirs(train_path, exist_ok=True)
os.makedirs(test_path, exist_ok=True)

split_ratio = 0.7

for class_name in os.listdir(combined_path):
    class_dir = os.path.join(combined_path, class_name)
    if not os.path.isdir(class_dir):
        continue
    images = os.listdir(class_dir)
    random.shuffle(images)

    split_index = int(len(images) * split_ratio)
    train_imgs = images[:split_index]
    test_imgs = images[split_index:]

    os.makedirs(os.path.join(train_path, class_name), exist_ok=True)
    os.makedirs(os.path.join(test_path, class_name), exist_ok=True)

    for img in train_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(train_path, class_name, img))
    for img in test_imgs:
        shutil.copy2(os.path.join(class_dir, img), os.path.join(test_path, class_name, img))

print("✅ Train/test split created.")


# Define image size and limits (ensure these are consistent with data preparation)
img_size = (64, 64)  # Using the image size from the Random Forest model
MAX_IMAGES_PER_CLASS = 500 # Using the limit from the Random Forest model

# Function to load images
def load_images_from_directory(directory):
    X, y = [], []
    for class_name in os.listdir(directory):
        class_path = os.path.join(directory, class_name)
        if not os.path.isdir(class_path): continue

        count = 0
        for filename in os.listdir(class_path):
            if count >= MAX_IMAGES_PER_CLASS:
                break
            file_path = os.path.join(class_path, filename)
            try:
                img = load_img(file_path, target_size=img_size)
                img_array = img_to_array(img) / 255.0
                X.append(img_array.flatten())
                y.append(class_name)
                count += 1
            except Exception as e:
                print("Skipping:", file_path, "| Error:", e)
    return np.array(X), np.array(y)

# Load data
print("📥 Loading training data...")
X_train, y_train = load_images_from_directory(train_path)

print("📥 Loading test data...")
X_test, y_test = load_images_from_directory(test_path)

print("✅ Data loaded.")
print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)

# Encode labels
encoder = LabelEncoder()
y_train_enc = encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)

print("🎯 Classes:", encoder.classes_)

# Apply PCA (ensure n_components is consistent)
pca = PCA(n_components=200)  # Using the number of components from the Random Forest model
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print("✅ PCA applied. New shapes:")
print("X_train_pca:", X_train_pca.shape)

# ✅ STEP: Train and Evaluate SVC (Support Vector Classifier)
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA


# Create the SVC model
svc = SVC(
    kernel='rbf',          # Radial basis function (most powerful default)
    C=1.0,                 # Regularization parameter
    gamma='scale',         # Kernel coefficient
    random_state=42
)

print("🚀 Training SVC...")
svc.fit(X_train_pca, y_train_enc)
print("✅ Model trained.")

# Predict on test data
y_pred = svc.predict(X_test_pca)
y_pred_labels = encoder.inverse_transform(y_pred)
y_test_labels = encoder.inverse_transform(y_test_enc)

# Evaluation
print("\n📊 Classification Report:")
print(classification_report(y_test_labels, y_pred_labels))

print("\n📉 Confusion Matrix:")
print(confusion_matrix(y_test_labels, y_pred_labels))

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=100, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                    random_state=1)
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)
clf.predict_proba(X_test[:1])
clf.predict(X_test[:5, :])
clf.score(X_test, y_test)

import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
X, y = make_classification(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    random_state=0)
clf = SVC(random_state=0)
clf.fit(X_train, y_train)
SVC(random_state=0)
predictions = clf.predict(X_test)
cm = confusion_matrix(y_test, predictions, labels=clf.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                              display_labels=clf.classes_)
disp.plot()
plt.show()